### ISSUE TITLE
Installation fails when zip is missing - consider adding requirements to install guidance

### ISSUE THREAD

**Issue by baywet** [asdf-community/asdf-kiota#8]
**Is your feature request related to a problem? Please describe.**

when running `asdf install kiota latest` it fails if zip is missing. 

```
.asdf/plugins/kiota/bin/download: line 23: unzip: command not found
```

**Describe the solution you'd like**

We could either add a known issues section to the documentation here, or requirements, or a more explicit error messages.

**Describe alternatives you've considered**

While solving for this is trivial if you have a bit of experience on linux OSes, I'm afraid it might deter new comers.

**Additional context**

On ubuntu `sudo apt-get install zip -y` did the trick.

**Comment by andreaTP** [comment]
`zip` is already listed in the [dependencies section](https://github.com/asdf-community/asdf-kiota#dependencies).

But it's super easy to add an early check and a more explicit message.
